name: ci 🚀

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
        name: checkout code 📥
      - name: install pnpm 📦
        uses: pnpm/action-setup@v4
        with:
          version: 9.5.0
      - name: setup node 🟢
        uses: actions/setup-node@v4
        with:
          node-version: "20.10.0"
          cache: "pnpm"
      - name: install dependencies 🔧
        run: pnpm install
      - name: run check ✅
        run: pnpm check
        env:
          SMTP_HOST: localhost
          SMTP_USER: test
          SMTP_PASS: test
          CF_TURNSTILE_SECRET: test
          CF_TURNSTILE_SITEKEY: test
          ADMIN_PASSWORD: test
          DB_URL: ":memory:"
