name: ci 🚀

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: checkout code 📥
      - name: install pnpm 📦
        uses: pnpm/action-setup@v4
        with:
          version: 9.5.0
      - name: setup node 🟢
        uses: actions/setup-node@v4
        with:
          node-version: "20.10.0"
          cache: "pnpm"
      - name: install dependencies 🔧
        run: pnpm install
      - name: run check ✅
        run: pnpm check

  create-plainweb:
    runs-on: ubuntu-latest
    steps:
      - name: install pnpm 📦
        uses: pnpm/action-setup@v4
        with:
          version: 9.5.0
      - name: setup node 🟢
        uses: actions/setup-node@v4
        with:
          node-version: "20.10.0"
      - name: create plainweb project 🪨
        run: |
          pnpm dlx create-plainweb@latest my-plainweb-project --yes --no-git-init
        env:
          npm_config_user_agent: ${{ github.actor }}
      - name: run build, test, and check 🚀
        run: |
          cd my-plainweb-project
          pnpm build
          pnpm test
          pnpm check
