name: ci 🚀

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
        name: checkout code 📥
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.29
      - name: install dependencies 🔧
        run: bun install
      - name: migrate ✅
        run: |
          timeout_cmd=""
          if [ "$RUNNER_OS" == "Windows" ]; then
            timeout_cmd="timeout 3"
          else
            timeout_cmd="timeout 3s"
          fi
          $timeout_cmd bun run example/0-todo.tsx || true
        shell: bash
      - name: build ✅
        run: bun run build
      - name: test ✅
        run: bun test
